---
# tasks file for roles/mariadb
 - name: "Install mariadb"
   #   become: yes
   yum: 
     name: "mariadb-server,MySQL-python"
     state: "installed"
 # Active le service MariaDB
 - name:  "start mariadb service"
   #  become: yes
   service: 
     name: "mariadb"
     state: "started"
     enabled: yes
